openapi: 3.0.3
info:
  title: Generation API
  version: 1.0.0
  description: |
    Contract for generating application materials (CV, cover letter, etc.) based on a job description and candidate profile.
paths:
  /generate-materials:
    post:
      summary: Generate application materials
      description: |
        Generates a tailored CV, cover letter, and other assets based on the provided job details and candidate profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '200':
          description: Materials successfully generated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratedAssets'
        '400':
          description: Invalid input data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable entity (e.g., generation failed).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unexpected server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GenerateRequest:
      type: object
      required:
        - job
        - profile
      properties:
        job:
          $ref: '#/components/schemas/JobInput'
        profile:
          $ref: '#/components/schemas/ProfileInput'

    JobInput:
      type: object
      required:
        - title
        - company
        - description
        - skills
      properties:
        id:
          type: string
        title:
          type: string
        company:
          type: string
        description:
          type: string
        skills:
          type: array
          items:
            type: string

    ProfileInput:
      type: object
      required:
        - cvText
      properties:
        name:
          type: string
        cvText:
          type: string
          description: The raw text content of the candidate's CV.

    GeneratedAssets:
      type: object
      required:
        - cv
        - coverLetter
        - networking
        - insights
        - matchScore
        - generatedAt
      properties:
        jobId:
          type: string
          description: Reference to the job ID if available.
        cv:
          type: string
          description: The tailored CV content in Markdown.
        coverLetter:
          type: string
          description: The tailored cover letter.
        networking:
          type: string
          description: Networking tips and conversation starters.
        insights:
          type: string
          description: Strategic insights for the application.
        matchScore:
          type: integer
          minimum: 0
          maximum: 100
          description: Compatibility score (0-100).
        generatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string
